on:
  push:
    branches:
        - 'main'
jobs:
  packer_build:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v2
      - run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - 
      - run: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - run: sudo apt-get update && sudo apt-get install packer
      - run: packer validate ami.json   
      - run: packer build ami.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AMI_USERS: ${{ secrets.AMI_USERS}}
          SUBNET_ID: ${{ secrets.SUBNET_ID}}
          SOURCE_AMI: ${{ secrets.SOURCE_AMI}}


            